[package]
name = "data_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.1"
rand = "0.8.5"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"