[package]
name = "data_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes = "0.7.5"
block-modes = "0.8.1"
rand = "0.8.5"
base64 = "0.13.0"
