[package]
name = "chronodb"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.13"
rust-ini = "0.21.0"
libc = "0.2"
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
regex = "1"