[package]
name = "data_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
num_cpus = "1.13"
mio = "0.8"
rayon = "1.7"
tokio = { version = "1", features = ["full"] }
